# Generated by Django 4.1.3 on 2022-11-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255)),
                ('description', models.CharField(default=None, max_length=255)),
                ('price', models.IntegerField(default=None)),
                ('rating', models.IntegerField(default=None)),
                ('image1', models.ImageField(default=None, upload_to='')),
                ('image2', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
