# Generated by Django 4.1.3 on 2022-12-16 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('pid_json', models.CharField(default=None, max_length=200)),
                ('price', models.IntegerField()),
                ('deliverycharges', models.IntegerField(null=True)),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('aid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='checkout.useraddress')),
            ],
        ),
    ]
